version: '3' # Specify the version of Docker Compose
services:
  mysql:
    image: mysql:5.7 # Use the MySQL 5.7 image
    environment:
      MYSQL_ROOT_PASSWORD: airflow_pass # Set the MySQL root password
      MYSQL_DATABASE: airflow_db # Create a database named airflow
      MYSQL_USER: airflow_user # Create a user named airflow
      MYSQL_PASSWORD: airflow_pass # Set the password for the airflow user
    ports:
      - "3366:3306" # Map the container port 3306 to the host port 3366
    volumes:
      - mysql-db-volume:/var/lib/mysql # Mount the MySQL data volume
    command: mysqld --sql_mode="ALLOW_INVALID_DATES"

# Define the Airflow webserver service
  airflow_webserver:
 # Build the Docker image using the Dockerfile in the current directory
   build:
   # Use the current directory as the build
     context: .
     # Specify the Dockerfile to use for the build
     dockerfile: Dockerfile
   
   ports:
     - "8070:8080"  # Map the container port 8080 to the host port 8070
   # Define the command to run when the container starts
   entrypoint: ./entrypoint.sh

volumes:
  mysql-db-volume: # Define the MySQL data volume


